initialize_assets:
  fields:
    overwrite:
      required: false
      default: true
      selector:
        boolean:
    backup:
      required: false
      default: true
      selector:
        boolean:

reinstall_assets:
  fields:
    backup:
      required: false
      default: true
      selector:
        boolean:

generate:

save_preset:
  fields:
    payload:
      required: true
      selector:
        object:

copy_preset:
  fields:
    source:
      required: true
      example: Dark Blue
      selector:
        text:
    name:
      required: true
      example: My Theme
      selector:
        text:

delete_user_theme:
  fields:
    name:
      required: true
      example: My Theme
      selector:
        text:

build_theme:
  fields:
    name:
      required: true
      example: My Theme
      selector:
        text:

refresh_catalogs:

copy_variant:
  fields:
    source:
      required: true
      example: dark
      selector:
        select:
          options:
            - light
            - dark

set_options:
  target:
    entity:
      integration: theme_studio
      domain: select
  fields:
    options:
      required: true
      example: '["None", "My Theme"]'
      selector:
        object:
