initialize_assets:
  fields:
    overwrite:
      required: false
      default: true
      selector:
        boolean:
    backup:
      required: false
      default: true
      selector:
        boolean:

reinstall_assets:
  fields:
    backup:
      required: false
      default: true
      selector:
        boolean:

save_preset:
  fields:
    payload:
      required: true
      selector:
        object:

delete_user_theme:
  fields:
    name:
      required: true
      example: My Theme
      selector:
        text:

build_theme:
  fields:
    name:
      required: true
      example: My Theme
      selector:
        text:

export_user_theme:
  fields:
    name:
      required: true
      example: My Theme
      selector:
        text:

import_user_theme:
  fields:
    data:
      required: false
      example: "TS1:eNp..."
      selector:
        text:
          multiline: true
    name:
      required: false
      example: Shared theme
      selector:
        text:

theme_from_image:
  fields:
    image:
      required: true
      example: orange-fade.jpg
      selector:
        text:
    name:
      required: false
      example: Autumn
      selector:
        text:
